# Introduction to _numpy_, _pandas_, and _matplotlib_

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
np, pd, plt

(<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>,
 <module 'pandas' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\__init__.py'>,
 <module 'matplotlib.pyplot' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\matplotlib\\pyplot.py'>)

## numpy datatypes
### float32

In [37]:
x = np.float32(2 ** 127)
x, type(x)

(1.7014118e+38, numpy.float32)

### float64

In [49]:
x = np.float64(2)**1024
x, type(x)

C:\Users\JLCat\AppData\Local\Temp\ipykernel_22308\3357549316.py:1: RuntimeWarning: overflow encountered in double_scalars
  x = np.float64(2)**1024


(inf, numpy.float64)

### arrays have a fixed datatype

In [52]:
lst = [1.,2.,3.,4.,5.]
array = np.array(lst)
array, type(array), array.dtype

(array([1., 2., 3., 4., 5.]), numpy.ndarray, dtype('float64'))

In [63]:
# np.arange creates array similar to how one would use a for loop // generator
## to create a list
start = 0
end = 100
interval = 10
range_array = np.arange(start,end + 1, interval)
range_array

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [64]:
# before we were making lists in this manner
range_list = [i for i in range(start,end + 1,interval)]
range_list

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

## two dimensional lists and arrays

### Create two dimensional list

In [67]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## transform that two dimensional list to a 
##  two dimensional array

In [69]:
two_dim_array = np.array(list_of_lists)
two_dim_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### call the 0th row of the two_dim_array

In [92]:
two_dim_array[0]

array([1, 2, 3])

### call the 0th element of the 0th row

In [95]:
two_dim_array[0][0]

1

### call the 1st element of the 0th row

In [94]:
two_dim_array[0][1]

2

### use a for loop to call the first index in the two_dim_array as $i$

### calling two_dim_array$[i]$ will yield the $i^{th}$ row

In [98]:
for i in range(len(two_dim_array)):
    print(i)
    print(two_dim_array[i])

0
[1 2 3]
1
[4 5 6]
2
[7 8 9]


### passing the row to a second for loop will cycle through 
### the second (row) index as $j$. Calling row$[j]$ will yield 
### the $j^{th}$ value from the row


In [88]:
print("i j:")
for i in range(len(two_dim_array)):
    row = two_dim_array[i]
    for j in range(len(row)):
        print(i,j)
        print("val:", row[j])

i j:
0 0
val: 1
0 1
val: 2
0 2
val: 3
1 0
val: 4
1 1
val: 5
1 2
val: 6
2 0
val: 7
2 1
val: 8
2 2
val: 9


In [99]:
for row in two_dim_array:
    print(row)
    for val in row:
        print(val)


[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


## np.zeros(), np.ones(), np.empty()

## np.zeros_like(e.g., list/array), np.ones_like(), np.empty_like()

In [101]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [103]:
np.empty((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [105]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [108]:
l = list_of_lists
np.zeros_like(l)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [110]:
np.ones_like((l))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [112]:
np.empty_like(l)

array([[16843009, 16843009, 16843009],
       [16843009, 16843009, 16843009],
       [16843009, 16843009, 16843009]])

## log values

In [114]:
np.log(1)

0.0

In [116]:
np.log(np.e)

1.0

In [118]:
np.log(two_dim_array)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [120]:
np.log10(two_dim_array)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [122]:
pi = np.pi
e = np.e
lne = np.log(e)
infinity = np.inf
null_val = np.nan
pi, e, lne, infinity, null_val

(3.141592653589793, 2.718281828459045, 1.0, inf, nan)